# hello-go-deploy-gce task-build-push.yml

platform: linux

# DOCKER BASE IMAGE FOR TASKS (BASED ON ALPINE, A SMALLER LINUX DISTRIBUTION)
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: hello-go-deploy-gce

outputs:
  - name: dist

run:
  path: ./hello-go-deploy-gce/ci/scripts/build-push.sh
  # args: [-debug]
