# hello-go-deploy-gce task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: jeffdecola/go-packer
    tag: latest

params:
  GOOGLE_APPLICATION_CREDENTIALS_FILE: "this will be overwritten"
  GOOGLE_JEFFS_PROJECT_ID: "this will be overwritten"
  GCE_GITHUB_VM_FILE: "this will be overwritten"
  GCE_GITHUB_VM_PUB_FILE: "this will be overwritten"

inputs:
- name: hello-go-deploy-gce

run:
  path: ./hello-go-deploy-gce/ci/scripts/deploy.sh
  # args: [-debug]

