# hello-go-deploy-gce task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: jeffdecola/hello-go-deploy-gce-packer-image
    tag: latest

inputs:
- name: hello-go-deploy-gce

run:
  path: ./hello-go-deploy-gce/ci/scripts/deploy.sh
  # args: [-debug]

