# hello-go-deploy-gce task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-gce

outputs:
- name: coverage-results

run:
  path: ./hello-go-deploy-gce/ci/scripts/unit-tests.sh
  # args: [-debug]
  