# hello-go-deploy-gce task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-gce

outputs:
- name: hello-go-deploy-gce-updated

run:
  path: ./hello-go-deploy-gce/ci/scripts/readme-github-pages.sh
  # args: [-debug]

