# hello-go-deploy-gce pipeline.yml

jobs:

- name: job-deploy
  plan:
    - get: hello-go-deploy-gce
      trigger: true
    - put: resource-slack-alert
      params:
        channel: '#jeff-builds'
        text: "From hello-go-deploy-gce: STARTED job-deploy in concourse ci."
    - put: resource-repo-status
      params: { state: "pending", description: "STARTED job-deploy in concourse ci.", commit: "hello-go-deploy-gce" }
    - task: task-deploy
      file: hello-go-deploy-gce/ci/tasks/task-deploy.yml
      params:
        GOOGLE_APPLICATION_CREDENTIALS_FILE: {{google_application_credentials_file}}
        GOOGLE_JEFFS_PROJECT_ID: {{google_jeffs_project_id}}
        GOOGLE_SERVICE_ACCOUNT_EMAIL_ADDRESS: {{google_service_account_email_address}}
        GCE_GITHUB_VM_FILE: {{gce_github_vm_file}}
        GCE_GITHUB_VM_PUB_FILE: {{gce_github_vm_pub_file}}
      on_success:
        do:
        - put: resource-slack-alert
          params:
            channel: '#jeff-builds'
            text: "From hello-go-deploy-gce: PASSED job-deploy in concourse ci."
        - put: resource-repo-status
          params: { state: "success", description: "PASSED job-deploy in concourse ci.", commit: "hello-go-deploy-gce" }
      on_failure:
        do:
        - put: resource-slack-alert
          params:
            channel: '#jeff-builds'
            text: "From hello-go-deploy-gce: FAILED job-deploy in concourse ci."
        - put: resource-repo-status
          params: { state: "failure", description: "FAILED job-deploy in concourse ci.", commit: "hello-go-deploy-gce" }

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master

resources:

- name: hello-go-deploy-gce
  type: git
  source:
    #uri: https://github.com/jeffdecola/hello-go-deploy-gce
    uri: git@github.com:jeffdecola/hello-go-deploy-gce.git
    branch: master
    private_key: {{git_private_key}}
- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}} 
- name: resource-repo-status 
  type: github-status
  source:
    repository: jeffdecola/hello-go-deploy-gce 
    access_token: {{repo_github_token}}
    